- name: NFS Mount
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/info.yaml
  tasks:
    - name:  vm mount nfs directory
      ansible.posix.mount:
        path: "{{ nfs_mount_dir }}"
        src: "{{ nfs_ip }}:/{{ nfs_volume }}"
        fstype: nfs
#        opts: _netdev
        state: mounted
